services:
  # Общие настройки Kafka для переиспользования в каждом брокере
  x-kafka-common:
    &kafka-common
    image: bitnami/kafka:3.7
    environment:
      &kafka-common-env
      # Включение режима KRaft (Kafka без Zookeeper)
      KAFKA_ENABLE_KRAFT: yes
      # Разрешение незашифрованных подключений
      ALLOW_PLAINTEXT_LISTENER: yes
      # Уникальный идентификатор KRaft-кластера (задан один раз при первом запуске)
      KAFKA_KRAFT_CLUSTER_ID: abdgfjtydksh
      # Протоколы для разных типов слушателей
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # Список слушателей для разных задач
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      # Роль узла: одновременно брокер и контроллер метаданных
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      # Контроллер использует listener CONTROLLER (для внутреннего кворума метаданных)
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # Участники кворума контроллеров
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      # Отключить автосоздание топиков
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: false
    networks:
      - proxynet
    healthcheck:
      test: ["CMD", "kafka-metadata-quorum.sh", "--bootstrap-server", "localhost:9092", "describe", "--status"]
      interval: 10s
      timeout: 10s
      retries: 10

  # Первый брокер Kafka
  kafka-0:
    <<: *kafka-common
    restart: always
    # Проброс EXTERNAL порта наружу (доступ извне)
    ports:
      - "127.0.0.1:9094:9094"
    environment:
      <<: *kafka-common-env
      # Уникальный ID узла внутри кластера
      KAFKA_CFG_NODE_ID: 0
      # Адреса, которые Kafka "рекламирует" наружу
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-0:9092,EXTERNAL://127.0.0.1:9094
    volumes:
      # Хранилище данных Kafka
      - kafka_0_data:/bitnami/kafka

  # 2 брокер Kafka
  kafka-1:
    <<: *kafka-common
    restart: always
    ports:
      - "127.0.0.1:9095:9094"
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,EXTERNAL://127.0.0.1:9095
    volumes:
      - kafka_1_data:/bitnami/kafka

  # 3 брокер Kafka
  kafka-2:
    <<: *kafka-common
    restart: always
    ports:
      - "127.0.0.1:9096:9094"
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,EXTERNAL://127.0.0.1:9096
    volumes:
      - kafka_2_data:/bitnami/kafka

  # Интерфейс управления Kafka (Kafka UI)
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    restart: always
    # Интерфейс доступен на localhost:8080
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      # Указываем, где искать брокер Kafka
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-0:9092,kafka-1:9092,kafka-2:9092
      # Название кластера в UI
      KAFKA_CLUSTERS_0_NAME: kraft
    depends_on:
      kafka-0:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
    networks:
      - proxynet

  # Schema Registry
  schema-registry:
    image: bitnami/schema-registry:7.6
    # API для регистрации/получения схем
    ports:
      - '127.0.0.1:8081:8081'
    environment:
      # Прослушивание запросов на порту 8081
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      # Список брокеров Kafka
      SCHEMA_REGISTRY_KAFKA_BROKERS: PLAINTEXT://kafka-0:9092,PLAINTEXT://kafka-1:9092,PLAINTEXT://kafka-2:9092
    depends_on:
      kafka-0:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
    networks:
      - proxynet

  # База данных PostgreSQL (источник данных)
  postgres:
    image: debezium/postgres:16
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      # Имя пользователя
      POSTGRES_USER: postgres-user
      # Пароль
      POSTGRES_PASSWORD: postgres-pw
      # Название базы данных
      POSTGRES_DB: customers
    volumes:
      - ./postgres/custom-config.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - proxynet

  debezium-ui:
    image: quay.io/debezium/debezium-ui:latest
    platform: linux/amd64
    container_name: debezium-ui
    ports:
      - "127.0.0.1:8085:8080"
    environment:
      KAFKA_CONNECT_URIS: http://kafka-connect:8083
    depends_on:
      - kafka-connect
    networks:
      - proxynet

  kafka-connect:
    build:
      context: ./kafka-connect
    ports:
      - "8083:8083"  # REST API Kafka Connect
      - "9875:9875"
      - "9876:9876"
    depends_on:
      - schema-registry
      - postgres
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka-0:9092,kafka-1:9092,kafka-2:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: 'kafka-connect'
      CONNECT_REST_ADVERTISED_HOST_NAME: 'localhost'

      # Хранение конфигурации, смещений и статусов
      CONNECT_CONFIG_STORAGE_TOPIC: 'connect-config-storage'
      CONNECT_OFFSET_STORAGE_TOPIC: 'connect-offset-storage'
      CONNECT_STATUS_STORAGE_TOPIC: 'connect-status-storage'
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1

      # Конвертеры
      CONNECT_KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"

      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081/'
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL:  'http://schema-registry:8081/'

      # Export JMX metrics to :9876/metrics for Prometheus
      KAFKA_JMX_PORT: '9875'
      KAFKA_OPTS: "-javaagent:/opt/jmx_prometheus_javaagent-0.15.0.jar=9876:/opt/kafka-connect.yml"
      # Read connection password from file
      CONNECT_CONFIG_PROVIDERS: "file"
      CONNECT_CONFIG_PROVIDERS_FILE_CLASS: "org.apache.kafka.common.config.provider.FileConfigProvider"

      # Пути к плагинам
      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/jars
    volumes:
      - ./confluent-hub-components/:/etc/kafka-connect/jars
    networks:
      - proxynet

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    links:
      - kafka-connect
    networks:
      - proxynet

  grafana:
    build:
      context: ./grafana
    ports:
      - "3000:3000"
    networks:
      - proxynet

networks:
  proxynet:
    # Общая пользовательская сеть Docker
    name: custom_network

volumes:
  kafka_0_data:
  kafka_1_data:
  kafka_2_data:
