services:
  # Общие настройки Kafka для переиспользования в каждом брокере
  x-kafka-common:
    &kafka-common
    image: bitnami/kafka:3.7
    environment:
      &kafka-common-env
      # Включение режима KRaft (Kafka без Zookeeper)
      KAFKA_ENABLE_KRAFT: yes
      # Разрешение незашифрованных подключений
      ALLOW_PLAINTEXT_LISTENER: yes
      # Уникальный идентификатор KRaft-кластера (задан один раз при первом запуске)
      KAFKA_KRAFT_CLUSTER_ID: abdgfjtydksh
      # Протоколы для разных типов слушателей
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # Список слушателей для разных задач
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      # Роль узла: одновременно брокер и контроллер метаданных
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      # Контроллер использует listener CONTROLLER (для внутреннего кворума метаданных)
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # Участники кворума контроллеров
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      # Отключить автосоздание топиков
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: false
    networks:
      - proxynet
    healthcheck:
      test: ["CMD", "kafka-metadata-quorum.sh", "--bootstrap-server", "localhost:9092", "describe", "--status"]
      interval: 10s
      timeout: 10s
      retries: 10

  # Первый брокер Kafka
  kafka-0:
    <<: *kafka-common
    restart: always
    # Проброс EXTERNAL порта наружу (доступ извне)
    ports:
      - "127.0.0.1:9094:9094"
    environment:
      <<: *kafka-common-env
      # Уникальный ID узла внутри кластера
      KAFKA_CFG_NODE_ID: 0
      # Адреса, которые Kafka "рекламирует" наружу
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-0:9092,EXTERNAL://127.0.0.1:9094
    volumes:
      # Хранилище данных Kafka
      - kafka_0_data:/bitnami/kafka

  # 2 брокер Kafka
  kafka-1:
    <<: *kafka-common
    restart: always
    ports:
      - "127.0.0.1:9095:9094"
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,EXTERNAL://127.0.0.1:9095
    volumes:
      - kafka_1_data:/bitnami/kafka

  # 3 брокер Kafka
  kafka-2:
    <<: *kafka-common
    restart: always
    ports:
      - "127.0.0.1:9096:9094"
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,EXTERNAL://127.0.0.1:9096
    volumes:
      - kafka_2_data:/bitnami/kafka

  # Интерфейс управления Kafka (Kafka UI)
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    restart: always
    # Интерфейс доступен на localhost:8080
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      # Указываем, где искать брокер Kafka
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-0:9092,kafka-1:9092,kafka-2:9092
      # Название кластера в UI
      KAFKA_CLUSTERS_0_NAME: kraft
    depends_on:
      kafka-0:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
    networks:
      - proxynet

  # База данных PostgreSQL (источник данных)
  postgres:
    image: debezium/postgres:16
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      # Имя пользователя
      POSTGRES_USER: postgres-user
      # Пароль
      POSTGRES_PASSWORD: postgres-pw
      # Название базы данных
      POSTGRES_DB: customers
    volumes:
      - ./postgres/custom-config.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - proxynet

# Добавляем NiFi
  nifi:
    image: apache/nifi:1.24.0
    container_name: nifi
    user: "root"
    ports:
      - "8082:8082"  # HTTP UI
    environment:
      NIFI_WEB_HTTP_PORT: 8082
    volumes:
      - nifi_logs:/opt/nifi/nifi-current/logs
      - nifi_data:/opt/nifi/nifi-current/data
      - ./nifi/drivers/postgresql-42.7.3.jar:/opt/nifi/nifi-current/lib/postgresql-42.7.3.jar
    networks:
      - proxynet
    depends_on:
      - kafka-0
      - postgres

networks:
  proxynet:
    # Общая пользовательская сеть Docker
    name: custom_network

volumes:
  kafka_0_data:
  kafka_1_data:
  kafka_2_data:
  nifi_data:
  nifi_logs:
